### ISSUE TITLE
Find out what Ticket and Source Code Versioning are

### ISSUE THREAD

**Issue by KasperSHenriksen** [AkuiChan/Mta17337pcssMini#8]
- Tickets - https://github.com/wp-e-commerce/wp-e-commerce/wiki/Creating-issue-tickets
- Source code versioning - The act of documenting the updates in the code. Often named with numbers. (e.g. minecraft updates 1.4.XXX)

**Comment by KasperSHenriksen** [comment]
We have sent our programming teacher an email about this.

**Comment by bgeisl16** [comment]
Found out that tickets are issue tickets :3 so we are already doing that

**Comment by AkuiChan** [comment]
Waiting for response from teacher to figure out what source code versioning is.
