### ISSUE TITLE
Write wiki/readme

### ISSUE THREAD

**Issue by KasperSHenriksen** [AkuiChan/Mta17337pcssMini#9]
- Description of our code.
- Write how to compile and run the code.

**Comment by bgeisl16** [comment]
Add
AkuiChan is Michelle Fly
Schonsteren is Kasper Schøn Henriksen
etc.
to the wiki

**Comment by AkuiChan** [comment]
Initial description needs to be revised after code is finished.

**Comment by AkuiChan** [comment]
Will use ReadMe instead of wiki. 

The initial description needs to be updated to the current version of the server and client

**Comment by bgeisl16** [comment]
- Check the line numbers
- How to compile
- How to run
